import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import Link from "next/link";
import React from "react";
import Nav from "@/app/nav/page";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: '123',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className={inter.className}>
      {Nav()}
      <main className="flex min-h-screen flex-col items-center justify-between p-12">
          <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
              {children}
          </div>
      </main>
      </body>
      </html>
  )
}
