import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import React from "react";
import Nav from "@/app/nav/page";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'OpenEASM',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <body className={inter.className}>
      {Nav()}
      <main className="flex flex-col  grid grid-cols-6 gap-4">
          <div className="col-start-2 col-span-4">
              {children}
          </div>
      </main>
      </body>
      </html>
  )
}
